In [1]:
import torch

Basic Manipulation

In [3]:
lst = list(range(10))
print(f"list:{lst}")

a= torch.tensor(lst)
print(f"torch tensor:{a}")

list:[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
torch tensor:tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Creating a 2D tensor (matrix)

In [10]:
tensor_2d = torch.tensor([[1,2,3],
                          [4,5,6]])
print(tensor_2d)
print(f"dimensions: {tensor_2d.ndimension()}")
print(f"shape: {tensor_2d.shape}")
print(f"size: {tensor_2d.size()}")

tensor([[1, 2, 3],
        [4, 5, 6]])
dimensions: 2
shape: torch.Size([2, 3])
size: torch.Size([2, 3])


Creating a 3D tensor

In [15]:
tensor_3d = torch.tensor([[[1,2,3],
                          [4,5,6]],
                          [[6,7,8],
                           [9,10,11]],
                          [[4,5,6],
                           [7,8,9]]])
print(tensor_3d)
print(f"dimensions: {tensor_3d.ndimension()}")
print(f"shape: {tensor_3d.shape}")
print(f"size: {tensor_3d.size()}")

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[ 4,  5,  6],
         [ 7,  8,  9]]])
dimensions: 3
shape: torch.Size([3, 2, 3])
size: torch.Size([3, 2, 3])


In [16]:
torch_4d = torch.tensor([[[[1,2,3],
                           [4,5,6]],
                           [[1,2,3],
                            [4,5,6]],
                          [[1,2,3],
                           [4,5,6]]]])
print(torch_4d)
print(f"dimensions: {torch_4d.ndimension()}")
print(f"shape: {torch_4d.shape}")
print(f"size: {torch_4d.size()}")

tensor([[[[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]]]])
dimensions: 4
shape: torch.Size([1, 3, 2, 3])
size: torch.Size([1, 3, 2, 3])
